on: push

jobs:
  build-containers:
    name: Build Docker Containers
    runs-on: ubuntu-latest # Fixed typo: 'runs-as' → 'runs-on'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
